---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  environments_path: "test/integration/environments"
  require_chef_omnibus: 11.10.4
  solo_rb:
    environment: test

platforms:
- name: canonical-ubuntu-14.04
  driver:
    box: canonical-ubuntu-14.04
    box_url: https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box
- name: ubuntu-13.10
- name: ubuntu-12.04
- name: debian-7.2.0
- name: centos-6.5

suites:
- name: default
  run_list:
  - recipe[apache2_test::default]
